baseURL = 'https://stepanovic.xyz'
languageCode = 'en-us'
title = 'Mike Stepanovic'
theme = 'minimal-blog'

[params]
  author = 'Mike Stepanovic'
  description = 'Welcome to my personal blog! I write about technology, ideas, and experiences that interest me.'
  email = 'mike@stepanovic.xyz'
  twitter = 'mikestepanovic'
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow HTML in markdown for custom tooltips

[menu]
  [[menu.main]]
    name = 'posts'
    url = '/posts/'
    weight = 10
  [[menu.main]]
    name = 'about'
    url = '/about/'
    weight = 20