baseURL = 'https://stepanovic.xyz'
languageCode = 'en-us'
title = 'Mike Stepanovic'
theme = 'minimal-blog'

[params]
  author = 'Mike Stepanovic'
  description = 'Welcome to my personal blog! I write about technology, ideas, and experiences that interest me.'
  email = 'mike@stepanovic.xyz'
  twitter = 'mikestepanovic'

[taxonomies]
  tag = 'tags'
  
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow HTML in markdown for custom tooltips

[menu]
  [[menu.main]]
    name = 'ideas'
    url = '/ideas/'
    weight = 10
  [[menu.main]]
    name = 'bio'
    url = '/bio/'
    weight = 20